spring:
  datasource:
    username: root
    password: Spx040610
    url: jdbc:mysql://rm-wz9az0py8eaz6yq6t2o.mysql.rds.aliyuncs.com:3306/exceltask?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver


    #配置mybatis相关路径
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml       # mybatis映射文件
  config-location: classpath:mybatis/mybatis-config.xml     # mybatis配置文件


server:
  port: 80




